TRAIN_NAME_LIST = {
    "SUBORNO": "SUBORNO EXPRESS (702)",
    "SONAR_BANGLA": "SONAR BANGLA EXPRESS (787)"
}

SEATS = {
    "SUVON_CHAIR": 7,
    "SNIGDHA": 3
}

CTG_T0_DHAKA = {
    "FROM": "Chattogram",
    "TO": "Dhaka"
}
DHAKA_TO_CTG = {
    "FROM": "Dhaka",
    "TO": "Chattogram"
}

CURRENT_TRAIN = TRAIN_NAME_LIST['SONAR_BANGLA']
CURRENT_JOURNEY = CTG_T0_DHAKA
FROM = CURRENT_JOURNEY['FROM']
TO = CURRENT_JOURNEY['TO']
JOURNEY_DATE = "16-Dec-2024"
